version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:latest-node-browsers

    working_directory: ~/repo
    branches:
      only:
        - master
        
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - setup_remote_docker:
         docker_layer_caching: true

      - run:
          name: Start server, make chromedriver executable and run tests
          command: |
            yarn
            yarn start &            
            cd seleniumMaven
            chmod +x chromedriver
            mvn test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always

      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit  
            
      - run:
          name: Docker Build
          command: |
            docker build -t mezzersmite/$FRONT_END_IMAGE_NAME:$TAG .

      - run:
          name: Push to docker hub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push mezzersmite/$FRONT_END_IMAGE_NAME:$TAG
