version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

     #   auth:
      #    username: $DOCKER_LOGIN
       #   password: $DOCKER_PWD

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - setup_remote_docker:
         docker_layer_caching: true

      - run:
          name: Docker Build
          command: |
            docker build -t mezzersmite/$FRONT_END_IMAGE_NAME:$TAG .

      - run:
          name: Push to docker hub
          command: |
            docker login -u $DOCKER_LOGIN -p $DOCKER_PWD
            docker push mezzersmite/$FRONT_END_IMAGE_NAME:$TAG

      # run tests!
      #- run: fun tests go here


